### ISSUE TITLE
我该如何添加一个子项

### ISSUE THREAD

**Issue by GuYun-D** [dishait/vuepress-docs-template#1]
*因为我是第一次使用您这个模板，而且我也是第一次接触vuepress*
<img width="960" alt="Snipaste_2022-05-10_17-40-59" src="https://user-images.githubusercontent.com/77197374/167600650-904fd8bb-a5cd-4ef0-b567-c72280a6e0d7.png">
我该怎么在这里创建一个子项，并且可以点击
如果您觉得要写很多的话，您可不可以帮我找一些相关的博客， 感谢

**Comment by markthree** [comment]
@GuYun-D 靓仔你好，可以过一遍 [vuepress文档](https://v2.vuepress.vuejs.org/zh/) 哦，具体在这个位置 👉 [页面](https://v2.vuepress.vuejs.org/zh/guide/page.html)
